# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100, null=True)),
                ('username', models.TextField(null=True)),
                ('text', models.TextField()),
                ('geo', models.TextField(null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
