# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='polarity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
