# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentalytics', '0002_tweet_polarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
