# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentalytics', '0004_auto_20171027_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
