# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentalytics', '0005_auto_20171027_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='tweet',
            name='polarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sentalytics.Polarity'),
        ),
    ]
