# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JumiaTweet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('text', models.TextField()),
                ('geo', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
