# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumiatweet',
            name='tweet_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jumiatweet',
            name='geo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jumiatweet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jumiatweet',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
